### ISSUE TITLE
ZIA provider ignores proxy

### ISSUE THREAD

**Issue by tetterev** [zscaler/terraform-provider-zia#100]
Hello,

ZIA provider seems to ignore http_proxy environment settings.
As you can see in the next line of the terraform debug it tries to resolve zscaler.net using the internal DNS server. 
The proper way is to delegate it to proxy as we dont resolve Internet names in the local corporate network.
Below there is also a curl based call to show that the proxy is defined and works. 

2022-06-02T15:15:39.215+0200 [DEBUG] provider.terraform-provider-zia_v2.0.3: 2022/06/02 15:15:39 [ERR] POST https://zsapi.zscaler.net/api/v1/authenticatedSession request failed: Post "https://zsapi.zscaler.net/api/v1/authenticatedSession": dial tcp: lookup zsapi.zscaler.net on 10.252.6.60:53: no such host

g441266@developer zia-guestwifi % terraform version    
Terraform v1.2.2
on darwin_amd64
  provider registry.terraform.io/zscaler/zia v2.0.3
g441266@developer zia-guestwifi % 
g441266@developer zia-guestwifi % curl https://zsapi.zscaler.net/api/v1/authenticatedSession
{"obfuscateApiKey":true}%                                                                                     
g441266@developer zia-guestwifi % echo $http_proxy
http://sec000.zone2.proxy:8080
g441266@developer zia-guestwifi % echo $https_proxy
http://sec000.zone2.proxy:8080
g441266@developer zia-guestwifi % 

Kind regards
Alex

**Comment by tetterev** [comment]
Same issue also on my SuSE Linux workstation with terraform v1.2.1

**Comment by willguibr** [comment]
Hi @tetterev Thanks for reaching out.
This issue seems unrelated to the provider itself, but more like a way Terraform actually behaves when operating behind a Proxy.
Please refer to the following articles, which may give you some direction on a potential resolution:
https://www.devopsschool.com/blog/using-http-and-https-proxy-in-terraform/
https://serverfault.com/questions/931493/use-a-proxy-with-terraform
Thank you

**Comment by willguibr** [comment]
Hi @tetterev I am doing some investigation, but it seems to be a common problem with Terraform itself and not the provider. Have attempted to run terraform init with another provider i.e Okta, or splunk? What was the outcome?
Here is a discussion in the Hashicorp community forum regarding this topic.
https://discuss.hashicorp.com/t/how-to-set-up-terraform-behind-proxy/20277

**Comment by tetterev** [comment]
Hi @willguibr,

terraform init is able to fetch the zia provider code using the same proxy config defined via https_proxy. aws provider works, aviatrix provider works. So terraform works in general. There is no defined proxy exception in no_proxy environment variable. Only access to zsapi.zscaler.net is ignoring proxy settings for some unknown reason. 
I think it can be easily tested even if your environment is not behind a proxy. Before running terraform apply define a faked invalid proxy with „export https_proxy=https://faked.proxy:8080“. If apply still works it means the code is ignoring proxy settings. If apply stopped working the code is trying to use the redirect via proxy that means all is good with the code.
