### ISSUE TITLE
zia resource for Local group missing.

### ISSUE THREAD

**Issue by maajin** [zscaler/terraform-provider-zia#104]
Hello Zia Team,

I have found **zia resource to create location group**  is missing in terraform registry & Zia Github page. I see there data block  but  not a resource.

Could it possible to add this resource?

![image](https://user-images.githubusercontent.com/4025241/173128539-f98cb417-1db3-4dbd-a252-e3d79fe26194.png)

**Comment by willguibr** [comment]
Hi @maajin There is currently no location_group API for POST/UPDATE/DELETE requests. A  location group can only be queried today based on API availability.
https://help.zscaler.com/zia/location-management#/locations/groups-get

**Comment by vitalemazo** [comment]
Was there an Update to this I have 100's of locations and sublocations the publications require the reference to the static  or dynamic groups .
