### ISSUE TITLE
 Error: un-successful request with status code: 400

### ISSUE THREAD

**Issue by maajin** [zscaler/terraform-provider-zia#107]
Unable to read location data using data block. Gives error 400

I have this location created in my zia portal but unable to read it using terraform.

data "zia_location_management" "locations" {

  name = "AWS-Development-us-east-1"

}

Error: un-successful request with status code: 400
│
│ with module.zia_sublocations.data.zia_location_management.locations,
│ on ..\..\..\modules\zia_sub_locations\current\main.tf line 40, in data "zia_location_management" "locations":
│ 40: data "zia_location_management" "locations" {

**Comment by willguibr** [comment]
Something wrong with your configuration, the data source is working as expected with version v2.1.1 and all other previous versions.
