### ISSUE TITLE
Cannot Import zia_traffic_forwarding_static_ip

### ISSUE THREAD

**Issue by chris-bornmann** [zscaler/terraform-provider-zia#115]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
[ec2-user@ip-10-0-3-15 tf]$ terraform -v
Terraform v1.2.4
on linux_amd64
+ provider registry.terraform.io/zscaler/zia v2.1.2
+ provider registry.terraform.io/zscaler/zpa v2.2.2

Your version of Terraform is out of date! The latest version
is 1.2.6. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)
- zia_traffic_forwarding_static_ip

### Terraform Configuration Files

```hcl
resource "zia_traffic_forwarding_static_ip" "zia_traffic_forwarding_static_ip_1_2_3_4" {
    ip_address      = "1.2.3.4"
    routable_ip     =  true
    comment         = ""
    geo_override    =  false
    latitude        =  20.123
    longitude       =  -100.456
}
```

### Debug Output
https://gist.github.com/chris-bornmann/f9f48d588c883d2697f302284a24f7fb

### Panic Output
n/a

### Expected Behavior
Resource should be imported into state file.

### Actual Behavior
Error and resource is not imported.

### Steps to Reproduce

1. `terraform import zia_traffic_forwarding_static_ip.zia_traffic_forwarding_static_ip_1_2_3_4 1.2.3.4`

### Important Factoids
n/a

### References
n/a

**Comment by willguibr** [comment]
@chris-bornmann  Thanks for reporting this issue.
We are working to get the import capability added to this resource and the fix will be included in the next release in the coming days. Thanks for your patience.
