### ISSUE TITLE
Issues with "terraform import zia_traffic_forwarding_static_ip"

### ISSUE THREAD

**Issue by chris-bornmann** [zscaler/terraform-provider-zia#121]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.2.4
on linux_amd64
+ provider registry.terraform.io/zscaler/zia v2.2.0
+ provider registry.terraform.io/zscaler/zpa v2.3.0

### Affected Resource(s)
- zia_traffic_forwarding_static_ip

### Terraform Configuration Files

```hcl
resource "zia_traffic_forwarding_static_ip" "zia_traffic_forwarding_static_ip_12_26_144_130" {
     ip_address      = "12.10.10.10"
     routable_ip     =  true
     comment         = "Import Test"
     geo_override    =  false
     latitude        =  39.9517
     longitude       =  -76.7064
}```

### Debug Output
https://gist.github.com/chris-bornmann/247459a046601194240d0f0a5e5ee4de

### Panic Output
n/a

### Expected Behavior
The contents of the state file should match the Terraform code (and actual resource in ZScaler) for an imported resource.  Running "terraform plan" should show no pending changes.

### Actual Behavior
After "terraform import" the state file has a null value for the comments field.  Running "terraform plan" shows that the comment field is going to change.

### Steps to Reproduce

1. `terraform import zia_traffic_forwarding_static_ip.zia_traffic_forwarding_static_ip_12_10_10_10 "12.10.10.10"`
2. `terraform state show zia_traffic_forwarding_static_ip.zia_traffic_forwarding_static_ip_12_10_10_10`
3. `terraform plan`

### Important Factoids
n/a

### References
n/a

**Comment by chris-bornmann** [comment]
I don't know why in the beta environment the latitude/longitude issue hasn't happened.  In production I see things like...

Original (in ZScaler and the TF code):
```
     latitude        =  39.9517
     longitude       =  -76.7064
```

Terraform state file after "terraform import":
```
     latitude     = 39.8851
     longitude    = -76.7187
```

They are all close, but none match 100%.

**Comment by willguibr** [comment]
Problem was solved without code intervention. Issue related to the automation method used for the resource import.
