### ISSUE TITLE
Import zia url custom category

### ISSUE THREAD

**Issue by Warok21** [zscaler/terraform-provider-zia#124]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

I have the following custom URL in my Zscaler: _**myTest**_
Now I want to import it with the following code
```
terraform {
  required_providers {
    zia = {
      source  = "zscaler/zia"
      version = "2.2.0"
    }
  }
}
resource "zia_url_categories" "myTest" {
 
}
```
This fails with the following error message:
│ Error: no custom url category found with name: myTest

When I look at the logs of this requests, I see following block:

> {
>   \"id\": \"CUSTOM_03\",
>   \"configuredName\": \"myTest\", 
>   \"keywords\": [
>    \"a new test\"
>   ],
>   \"keywordsRetainingParentCategory\": [],
>   \"urls\": [
>    \"test.xxx\"
>   ],
>   \"dbCategorizedUrls\": [],
>   \"customCategory\": true,
>   \"editable\": true,
>   \"description\": \"Description\",
>   \"type\": \"URL_CATEGORY\",
>   \"val\": 130,
>   \"customUrlsCount\": 1,
>   \"urlsRetainingParentCategoryCount\": 0,
>   \"customIpRangesCount\": 0,
>   \"ipRangesRetainingParentCategoryCount\": 0
>  },

As you can see, there is no field "name" and I think that's why I cannot import my ressource.
Could you please fix this? I don't want to work with the ID ;) 

### New or Affected Resource(s)

 terraform version
Terraform v1.2.8
on linux_amd64
 provider registry.terraform.io/zscaler/zia v2.2.0

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- #0000

**Comment by willguibr** [comment]
@Warok21 
Because this is a "USER_DEFINED" category, you must define the following parameter in your HCL configuration as the example below:

```hcl
resource "zia_url_categories" "myTest" {
  super_category  = "USER_DEFINED"
  configured_name = "myTest"
  description     = "myTest"
  custom_category = true
  editable        = true
  type            = "URL_CATEGORY"
  urls = [
    "test.xxx"
  ]
}
```

**Comment by Warok21** [comment]
@willguibr , thanks for the reply.
As you said, I added this part to my file, but even with these lines, the field _urls_ in the terraform.tfstate is empty.
To be precise, I used this command:  `terraform import  zia_url_categories.Configured_Name  "USER_DEFINED"`
Can you help me with that?

**Comment by willguibr** [comment]
@Warok21 Currently importing zia_url_categories can only be done via id i.e:

```sh
terraform import zia_url_categories.example1 "CUSTOM_06"

terraform import zia_url_categories.example2 "OTHER_ENTERTAINMENT_AND_RECREATION"
```
We'll be looking in implementing more optimal ways to import url categories in upcoming versions.
