### ISSUE TITLE
zia_firewall_filtering_network_application_groups name not recognized as set?

### ISSUE THREAD

**Issue by chris-bornmann** [zscaler/terraform-provider-zia#128]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
$ terraform -v
Terraform v1.3.0
on linux_amd64
+ provider registry.terraform.io/zscaler/zia v2.2.0
+ provider registry.terraform.io/zscaler/zpa v2.3.0

### Affected Resource(s)

- zia_firewall_filtering_network_application_groups

### Terraform Configuration Files

```hcl
resource "zia_firewall_filtering_network_application_groups" "zia_firewall_filtering_network_application_groups_Microsoft_Office365" {
    name = "Microsoft Office365"
    description = "Microsoft Office365"
    network_applications = [
        "OFFICE365",
        "ONEDRIVE",
        "OUTLOOK",
        "SHAREPOINT",
        "SHAREPOINT_ADMIN",
        "SHAREPOINT_BLOG",
        "SHAREPOINT_CALENDAR",
        "SHAREPOINT_DOCUMENT",
        "SHAREPOINT_ONLINE",
        "SKYPE_FOR_BUSINESS",
        "YAMMER"
    ]
}```

### Debug Output
https://gist.github.com/chris-bornmann/d1ea0e5444ccd11da84e59d311c7cb51

### Panic Output
N/A

### Expected Behavior
The "terraform plan" command should report no changes need to be made because the name attribute is already set.

### Actual Behavior
The "terraform plan" command says that the name attribute needs to be set.

### Steps to Reproduce

<!--- Please list the steps required to reproduce the issue. --->

1. `terraform plan`

### Important Factoids
N/A

### References
N/A

**Comment by willguibr** [comment]
Commenting so the issue remains open for a little longer.

**Comment by willguibr** [comment]
Hi @chris-bornmann 
I have used the same configuration snippet you provided above, and I did not identify any drift issues as you can see in the below screenshot. If the issue still persists, I am happy to reopen this Issue or have an offline conversation to investigate.
Thanks
<img width="929" alt="Screen Shot 2023-02-11 at 4 28 51 PM" src="https://user-images.githubusercontent.com/23208337/218286831-3911bb9a-b61d-40a2-8086-b1661431dce9.png">
