### ISSUE TITLE
Changes to zia_firewall_filtering_rule.dest_ip_groups Not Recognized

### ISSUE THREAD

**Issue by chris-bornmann** [zscaler/terraform-provider-zia#142]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.3.0
on darwin_amd64
+ provider registry.terraform.io/zscaler/zia v2.2.3
+ provider registry.terraform.io/zscaler/zpa v2.4.0

### Affected Resource(s)
- zia_firewall_filtering_rule

### Terraform Configuration Files
```hcl
resource "zia_firewall_filtering_destination_groups" "foo" {
    name         = "foo"
    description  = "foo"
    type         = "DSTN_IP"
    addresses    = [
        "10.0.0.0/8"
    ]
}

resource "zia_firewall_filtering_rule" "zia_firewall_filtering_rule_Default_Firewall_Filtering_Rule" {
    name = "Default Firewall Filtering Rule"
    description = ""
    order = -1

    action = "BLOCK_DROP"
    enable_full_logging = false
    rank = 7
    state = "ENABLED"
}

resource "zia_firewall_filtering_rule" "bar" {
    name = "bar"
    description = "bar"
    order = 1

    action = "BLOCK_RESET"
    enable_full_logging = false
    rank = 7
    state = "ENABLED"
    dest_ip_groups {
        id = [
            zia_firewall_filtering_destination_groups.foo.id
        ]
    }
}
```

### Debug Output
https://gist.github.com/chris-bornmann/a1d4581844ce75594f2c5e674c9ac5b9

### Panic Output
N/A

### Expected Behavior
"terraform plan" should show that the dest_ip_groups are changing.

### Actual Behavior
"terraform plan" says "No changes.  Your infrastructure matches the configuration."

### Steps to Reproduce
1. Edit zia_firewall_fiiltering_rule's dest_ip_groups attribute to removing the destination IP groups referenced.
1. `terraform plan`

### Important Factoids
I'm think this used to work before I upgraded my ZIA provider.

### References
N/A

**Comment by willguibr** [comment]
Hi @chris-bornmann the behavior of this resource has not changed. I just tested with your configuration and add or removing new addresses the ``terraform plan`` shows that changes will occur.
William

**Comment by chris-bornmann** [comment]
@willguibr - The issue is not with adding/removing the destination groups themselves (ie: the zia_firewall_filtering_destination_groups resource).  The issue is with changes to the zia_firewall_filtering_rule resource's dest_ip_groups attribute.  Removing a destination group from that attribute doesn't register as a change so the plan comes back with nothing to do.

In addition, adding new destination groups to a firewall rule, which does result in recognized work to perform, shows up as a "remove and add" of any existing destination groups too, which could cause confusion.  It seems like only the things that are changing should show up as a "+" or "-" in the plan.
