### ISSUE TITLE
Group not found

### ISSUE THREAD

**Issue by louiskim-levu-phx** [zscaler/terraform-provider-zia#159]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- data zia_group_management

### Expected Behavior

Terraform can data source any group by name

### Actual Behavior
Some groups are not found while others are.

```
│ Error: no group found with name: XXX
```

### repeat the problem
Create 101 groups in the org, verify that the 100th group can be data sourced but not the 101th.

### Reason
The data source uses GetGroups which get all groups but the default pagesize is 100.

### Solution
Use this GetGroupByName instead of GetGroups can solve the issue.

**Comment by willguibr** [comment]
Hi @louiskim-levu-phx Thanks for reporting this issue.
I found out the issue, and will be releasing a new fix in the next release of the provider v2.3.2.
Let us know if you experience any further issues.
William

**Comment by louiskimlevu** [comment]
thanks @willguibr !

**Comment by willguibr** [comment]
Hi @louiskimlevu @louiskim-levu-phx We have implemented a fix for the pagination issue you've reported. Please update your configuration file to v2.3.5. I'll reopen the issue temporarily until you can validate fix.
Thank you

**Comment by louiskim-levu-phx** [comment]
It is working with 2.3.5. You can close this bug. Thanks!

**Comment by willguibr** [comment]
Thank you @louiskimlevu @louiskimlevu Thanks for the update. 
Feel free to reach out via email as well wguilherme@you_know_the_rest.com ;)
