### ISSUE TITLE
No ASCII url failed

### ISSUE THREAD

**Issue by Renizmy** [zscaler/terraform-provider-zia#170]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- zia_url_categories

### Terraform Configuration Files

```hcl
resource "zia_url_categories" "TEST" {
  super_category  = "USER_DEFINED"
  configured_name = "NAME"
  description     = "DESCRIPTION"
  custom_category = true
  type            = "URL_CATEGORY"
  editable        = false
  urls            = ["noël.cloud", "radada .cloud"]
}
```

### Expected Behavior

Translate urls with punycode (https://github.com/golang/net/blob/master/idna/punycode.go) or fail on terraform plan
https://www.rfc-editor.org/rfc/rfc3492

### Actual Behavior

Error: FAILED: PUT, [..] {"code":"INVALID_INPUT_ARGUMENT","message":"Invalid urls [noël.cloud]"}, api responded with code: 400

**Comment by willguibr** [comment]
Hi  @Renizmy The ZIA API  and UI does not support this types of characters; hence, there's nothing in the source code we can do, as it is enforced upstream. If there's a valid use case/business case, I'd recommend to contact your TAM (Technical Account Manager) or SE and ask them to raise an ER (Enhancement Request) for analysis by engineering.
<img width="583" alt="Screen Shot 2023-01-28 at 9 57 22 AM" src="https://user-images.githubusercontent.com/23208337/215283214-bc6b45fc-996e-4bff-84c6-84b74055bacb.png">

Let me know if you have any further questions, and feel free to contact me via email as well wguilherme@you_know_the_rest.com ;)
