### ISSUE TITLE
resource zia_firewall_filtering_rule

### ISSUE THREAD

**Issue by francesco-supportlan** [zscaler/terraform-provider-zia#186]
Hi,

I'm trying to push some rules.
All date are in a json file that looks like: (just a sample)

[{"idseq":"021","id":21,"name":"TEST1","label":"GLOBAL","location":["LOC1", "LOC2"],"services":["HTTP", "HTTPS"],"applications":["ANY"],"src_obj":["HOST_1", "HOST_2"],"dst_obj":["ANY"],"url_category":["ANY"],"country":["ANY"],"action":"ALLOW","object_name":"NATIVE"}, 
 {"idseq":"022","id":22,"name":"TEST2","label":"GLOBAL","location":["LOC1", "LOC2"],"services":["OBJ_1"],"applications":["ANY"],"src_obj":["HOST_3"],"dst_obj":["ANY"],"url_category":["ANY"],"country":["ANY"],"action":"ALLOW","object_name":"OBJ"}, 
 {"idseq":"023","id":23,"name":"TEST3","label":"GLOBAL","location":["LOC1", "LOC2"],"services":["NTP-UDP"],"applications":["ANY"],"src_obj":["HOST_3"],"dst_obj":["HOST_7", "HOST_8"],"url_category":["ANY"],"country":["ANY"],"action":"ALLOW","object_name":"OBJ"}, 
 {"idseq":"024","id":24,"name":"TEST4","label":"GLOBAL","location":["LOC1", "LOC2"],"services":["ANY"],"applications":["ANY"],"src_obj":["HOST_1", "HOST_2"],"dst_obj":["ANY"],"url_category":["ANY"],"country":["ANY"],"action":"BLOCK_DROP","object_name":"OBJ"}, 
 {"idseq":"025","id":25,"name":"TEST5","label":"GLOBAL","location":["LOC1", "LOC2"],"services":["OBJ_2"],"applications":["ANY"],"src_obj":["ANY"],"dst_obj":["ANY"],"url_category":["ANY"],"country":["ANY"],"action":"ALLOW","object_name":"GROUP"}, 
 {"idseq":"026","id":26,"name":"TEST6","label":"GLOBAL","location":["LOC1", "LOC2"],"services":["QUIC"],"applications":["ANY"],"src_obj":["HOST_3"],"dst_obj":["ANY"],"url_category":["ANY"],"country":["ANY"],"action":"ALLOW","object_name":"NATIVE"}, 
 {"idseq":"027","id":27,"name":"TEST7","label":"GLOBAL","location":["LOC1", "LOC2"],"services":["OBJ_RDP"],"applications":["ANY"],"src_obj":["HOST_3"],"dst_obj":["HOST_6"],"url_category":["ANY"],"country":["ANY"],"action":"ALLOW","object_name":"OBJ"}, 
 {"idseq":"028","id":28,"name":"TEST8","label":"GLOBAL","location":["LOC1", "LOC2"],"services":["OBJ_3", "OBJ_4"],"applications":["ANY"],"src_obj":["HOST_4", "HOST_5"],"dst_obj":["ANY"],"url_category":["ANY"],"country":["ANY"],"action":"ALLOW","object_name":"OBJ"}, 
 {"idseq":"029","id":29,"name":"TEST9","label":"GLOBAL","location":["LOC1", "LOC2"],"services":["OBJ_5"],"applications":["ANY"],"src_obj":["ANY"],"dst_obj":["ANY"],"url_category":["ANY"],"country":["ANY"],"action":"ALLOW","object_name":"GROUP"}
]

My configuration on terraform is:

resource "zia_firewall_filtering_rule" "firewall_deploy" {
    depends_on = [
      data.zia_rule_labels.export_label_info,
      data.zia_location_groups.export_location_info,
      data.zia_firewall_filtering_network_service.fetch_objects_id,
      data.zia_firewall_filtering_network_application.fetch_apps,
    ]
    for_each = {for row in local.local_data_zia_firewall_rules : row.idseq => row}
    name                = each.value.name
    description         = "Migrated rules"
    action              = each.value.action
    state               = "ENABLED"
    order               = each.value.id
    enable_full_logging = true
    location_groups {
      id = flatten([
            for location_grp in each.value.location :
                data.zia_location_groups.export_location_info[location_grp].id
        ])
    }
    labels { 
      id = [data.zia_rule_labels.export_label_info[each.value.label].id]
    }
    nw_services {
      id = flatten([
            for svce in each.value.services :
               each.value.object_name != "GROUP" ? [ (svce != "ANY" ? [ data.zia_firewall_filtering_network_service.fetch_objects_id[svce].id ] : []) ] : []
      ])
    }
    nw_service_groups {
      id = flatten([
            for svce in each.value.services :
               each.value.object_name == "GROUP" ? [ (svce != "ANY" ? [ zia_firewall_filtering_network_service_groups.svce_group[svce].id ] : []) ] : []
      ])
    }    
    src_ip_groups {
      id = flatten([
            for srcobj in each.value.src_obj :
                srcobj != "ANY" ? [zia_firewall_filtering_ip_source_groups.src_ip_addresses[srcobj].id] : []
      ])
    }
    dest_ip_groups {
      id = flatten([
            for dstobj in each.value.dst_obj :
                dstobj != "ANY" ? [zia_firewall_filtering_destination_groups.dstn_fqdn_ip_addresses[dstobj].id] : []
      ])
    }
}

When deploying, I'm stuck with this:

zia_firewall_filtering_rule.firewall_deploy["054"]: Still creating... [8m0s elapsed]
zia_firewall_filtering_rule.firewall_deploy["066"]: Still creating... [8m0s elapsed]
zia_firewall_filtering_rule.firewall_deploy["097"]: Still creating... [8m0s elapsed]
zia_firewall_filtering_rule.firewall_deploy["037"]: Still creating... [8m0s elapsed]
zia_firewall_filtering_rule.firewall_deploy["076"]: Still creating... [8m0s elapsed]
zia_firewall_filtering_rule.firewall_deploy["059"]: Still creating... [8m0s elapsed]
zia_firewall_filtering_rule.firewall_deploy["041"]: Still creating... [8m0s elapsed]
zia_firewall_filtering_rule.firewall_deploy["076"]: Still creating... [8m10s elapsed]
zia_firewall_filtering_rule.firewall_deploy["067"]: Still creating... [8m10s elapsed]
zia_firewall_filtering_rule.firewall_deploy["115"]: Still creating... [8m10s elapsed]
zia_firewall_filtering_rule.firewall_deploy["028"]: Still creating... [8m10s elapsed]
zia_firewall_filtering_rule.firewall_deploy["054"]: Still creating... [8m10s elapsed]
zia_firewall_filtering_rule.firewall_deploy["066"]: Still creating... [8m10s elapsed]
zia_firewall_filtering_rule.firewall_deploy["097"]: Still creating... [8m10s elapsed]
zia_firewall_filtering_rule.firewall_deploy["037"]: Still creating... [8m10s elapsed]
zia_firewall_filtering_rule.firewall_deploy["059"]: Still creating... [8m10s elapsed]
zia_firewall_filtering_rule.firewall_deploy["041"]: Still creating... [8m10s elapsed]
zia_firewall_filtering_rule.firewall_deploy["041"]: Still creating... [8m20s elapsed]
zia_firewall_filtering_rule.firewall_deploy["054"]: Still creating... [8m20s elapsed]
zia_firewall_filtering_rule.firewall_deploy["037"]: Still creating... [8m20s elapsed]
zia_firewall_filtering_rule.firewall_deploy["059"]: Still creating... [8m20s elapsed]
zia_firewall_filtering_rule.firewall_deploy["028"]: Still creating... [8m20s elapsed]
zia_firewall_filtering_rule.firewall_deploy["067"]: Still creating... [8m20s elapsed]
zia_firewall_filtering_rule.firewall_deploy["097"]: Still creating... [8m20s elapsed]
zia_firewall_filtering_rule.firewall_deploy["076"]: Still creating... [8m20s elapsed]
zia_firewall_filtering_rule.firewall_deploy["115"]: Still creating... [8m20s elapsed]

and keeps going without errors and sometimes I get errors: 

│ Error: FAILED: POST, https://xxxxxxxxx/api/v1/firewallFilteringRules, 400, 400 , {"code":"INVALID_INPUT_ARGUMENT","message":"Rule is not allowed at order 107"}, api responded with code: 400
│
│   with zia_firewall_filtering_rule.firewall_deploy["107"],
│   on main.tf line 146, in resource "zia_firewall_filtering_rule" "firewall_deploy":
│  146: resource "zia_firewall_filtering_rule" "firewall_deploy" {
│
╵
╷
│ Error: FAILED: POST, https://xxxxxxxxx/api/v1/firewallFilteringRules, 400, 400 , {"code":"INVALID_INPUT_ARGUMENT","message":"Rule is not allowed at order 109"}, api responded with code: 400
│
│   with zia_firewall_filtering_rule.firewall_deploy["109"],
│   on main.tf line 146, in resource "zia_firewall_filtering_rule" "firewall_deploy":
│  146: resource "zia_firewall_filtering_rule" "firewall_deploy" {
│
╵

It seems it can't push rules in the right order.

Any ideas?

**Comment by willguibr** [comment]
Hi @francesco-supportlan 
Can you please update your configuration to use the latest provider version v2.4.2? This issue has been addressed in this latest release.
Thank you

**Comment by francesco-supportlan** [comment]
I'm using the 2.4.2

**Comment by willguibr** [comment]
Can you reach out via email wguilherme@you_know_the_rest.com with a configuration sample so I can try reproduce the problem?

**Comment by francesco-supportlan** [comment]
email sent

**Comment by willguibr** [comment]
Received Thanks. I’ll investigate and send an update as soon as possible.

**Comment by francesco-supportlan** [comment]
When doing a trace I see the following error: INVALID_INPUT_ARGUMENT.

If I execute the same code but I keep only 1 line in my json (the one which was giving me the error invalid_input_argument), it works.

So it is the whole json handling which causes the issue

**Comment by alasta** [comment]
Hi,
I think it a dependencies problem in deplloyement rule, Terraform try to parallized the rules deployement and there is a order rule which not the next order.
Example :
- rule 1, rule 2, rule 3, rule 4 .... : OK
- rule 1, rule 2, rule 4, rule 3 ... : I think is your problem

Best regards

**Comment by willguibr** [comment]
Issue fixed on version v2.4.6
