### ISSUE TITLE
zia_firewall_filtering_rule - description name isn't correct

### ISSUE THREAD

**Issue by alasta** [zscaler/terraform-provider-zia#190]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

All

### Affected Resource(s)

- zia_firewall_filtering_rule

### Terraform Configuration Files

N/A
### Steps to Reproduce

Read the module documentation : 
Name : (Required) Name of the network service group

**Comment by alasta** [comment]
It's a typography error in the documentation on the "Name" definition.

Best regards

**Comment by willguibr** [comment]
Fixed in version v2.5.0
