### ISSUE TITLE
zia_firewall_filtering_rule - where get the app_services ID

### ISSUE THREAD

**Issue by alasta** [zscaler/terraform-provider-zia#191]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- zia_firewall_filtering_rule

### Terraform Configuration Files

resource "zia_firewall_filtering_rule" "example" {
    name                = "Example"
    description         = "Example"
    action              = "ALLOW"
    state               = "ENABLED"
    order               = 1
    enable_full_logging = true
    app_services {
        id  = [ ID OF RESOURCES1 ]
}

### Steps to Reproduce

1. `terraform apply`

### References

Where collect the ID apps_services, I don't found it in data source ?

**Comment by willguibr** [comment]
Hi @alasta Thanks for opening the issue.
The attribute ``app_services `` is supported by the following API endpoint /appServices/lite along with ``app_services_group`` /appServiceGroups/lite. Both of these endpoints are actually undocumented in the public Swagger; however, they are available.
I have included two new data sources in PR #193 to support these attributes:

- app_services - zia_firewall_filtering_application_services
- app_service_groups - zia_firewall_filtering_application_services_group

Please check the [CHANGELOG for v2.4.3](https://github.com/zscaler/terraform-provider-zia/blob/master/CHANGELOG.md)

Also feel free to reach out via wguilherme@you_know_the_rest.com ;)

**Comment by alasta** [comment]
Hi @willguibr ,

Thank you to this terraform update !
I test that the next week.
Best regards

**Comment by alasta** [comment]
Hi,
I don't see this data sources in terraform registry, it's normal ?
Best regards
