### ISSUE TITLE
zia_firewall_filtering_rule - incorrect definition of argument dest_ip_categories

### ISSUE THREAD

**Issue by alasta** [zscaler/terraform-provider-zia#192]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- zia_firewall_filtering_rule

### Terraform Configuration Files

```hcl
resource "zia_firewall_filtering_rule" "this" {
    name                = var.name
    description       = var.description
    action               = var.action
    state                 = var.state
    order               = var.order
    enable_full_logging = var.enable_full_logging 
    dest_ip_categories {
        id  = var.dest_ip_categories_id
    }
```

### Panic Output

The terraform validate:  
```
│ Error: Unsupported block type
│ 
│   on modules/fw_rules/main.tf line 34, in resource "zia_firewall_filtering_rule" "this":
│   34:     dest_ip_categories {
│ 
│ Blocks of type "dest_ip_categories" are not expected here. Did you mean to
│ define argument "dest_ip_categories"? If so, use the equals sign to assign
│ it a value.
```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids
The document explain :
```
[dest_ip_categories](https://registry.terraform.io/providers/zscaler/zia/latest/docs/resources/zia_firewall_filtering_rule#dest_ip_categories)** - (Optional) [id](https://registry.terraform.io/providers/zscaler/zia/latest/docs/resources/zia_firewall_filtering_rule#id)entify destinations based on the URL category of the domain, select Any to apply the rule to all categories or select the specific categories you want to control.

id - (String) Identifier that uniquely identifies an entity
```
Source : https://registry.terraform.io/providers/zscaler/zia/latest/docs/resources/zia_firewall_filtering_rule#argument-reference

### The good terraform configuration to use actually 
```hcl
resource "zia_firewall_filtering_rule" "this" {
    name                = var.name
    description       = var.description
    action               = var.action
    state                 = var.state
    order               = var.order
    enable_full_logging = var.enable_full_logging 
    dest_ip_categories = var.dest_ip_categories_id     ### list
}
```

**Comment by willguibr** [comment]
Hi @alasta Thanks for opening this issue. It is only a documentation problem. So, it will be fixed in the next minor release.
Be aware that the dest_ip_categories, only support Custom URL Categories as per the below example. In other words, built-in categories i.e "PHISHING" etc are not supported as per the API definition.
```hcl
resource "zia_firewall_filtering_rule" "this" {
    name = "Example2"
    description = "Example2"
    action = "ALLOW"
    state = "ENABLED"
    order = 1
    rank = 7
    enable_full_logging = true
    dest_ip_categories = [data.zia_url_categories.custom_01.id, data.zia_url_categories.custom_02.id]
}

data "zia_url_categories" "custom_01"{
    id = "CUSTOM_01"
}

data "zia_url_categories" "custom_02"{
    id = "CUSTOM_02"
}
```

**Comment by alasta** [comment]
Hi @willguibr ,

Thank you to information and reactivity, at this time not a use case the built-in categories ;).
I check the API definition to know if a feature maybe coming.
Best regards
