### ISSUE TITLE
zia_location_management - error with  ip_addresses after update provider > 2.4.2

### ISSUE THREAD

**Issue by alasta** [zscaler/terraform-provider-zia#203]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.2.2
### Affected Resource(s)

- zia_location_management

### Terraform Configuration Files

```hcl
resource "zia_location_management" "usa_sjc37_office_branch01"{
    name = "USA_SJC37_Office-Branch01"
    description = "Created with Terraform"
    country = "UNITED_STATES"
    tz = "UNITED_STATES_AMERICA_LOS_ANGELES"
    profile = "CORPORATE"
    parent_id = data.zia_location_management.usa_sjc37.id
    auth_required = true
    idle_time_in_minutes = 720
    display_time_unit = "HOUR"
    surrogate_ip = true
    ofw_enabled = true
    ip_addresses = [ "10.5.0.0-10.5.255.255" ]
}
```

### Debug Output

```hcl
Error: expected ip_addresses.0 to contain a valid IPv4 address, got: 10.5.0.0-10.5.255.255
│ 
│   with zia_location_management.usa_sjc37_office_branch01,
│   on main-location.tf line 126, in resource "zia_location_management" "usa_sjc37_office_branch01":
│  126:   ip_addresses         = ["10.5.0.0-10.5.255.255"]
│ 
╵
[ ERROR ] > validate failed
```

### Expected Behavior

I want used the last provider to use the last update.

### Steps to Reproduce

This code work with provider 2.4.2 but not after.

**Comment by willguibr** [comment]
Please use the latest version v.2.4.6.
This issue has been resolved in this version.

**Comment by willguibr** [comment]
If you're referring to the resource: zia_traffic_forwarding_gre_tunnel, there's no need to specify the primary_dest_vip and secondary_dest_vip, as the provider automatically let ZIA select that on your behalf.
Here's a working configuration.

Step 1: Create the Static IP
```hcl
resource "zia_traffic_forwarding_static_ip" "this" {
  comment        = "GRE Tunnel Created with Terraform"
  geo_override = true
  ip_address     = "xxx.xxx.xxx.xxx"
  latitude           = 49.0526
  longitude        = -122.8291
}
```
Step 2: Create the GRE Tunnel
```hcl
resource "zia_traffic_forwarding_gre_tunnel" "this" {
  comment               = "GRE Tunnel Created with Terraform"
  ip_unnumbered     = true
  source_ip               = zia_traffic_forwarding_static_ip.this.ip_address
  within_country       = false
  country_code         = "CA"
  depends_on           = [ zia_traffic_forwarding_static_ip.this ]
}
```

Step 3: Create the Location
```hcl
resource "zia_location_management" "this"{
    name = "USA_LAS_01"
    description = "Created with Terraform"
    country = "UNITED_STATES"
    tz = "UNITED_STATES_AMERICA_LOS_ANGELES"
    profile = "CORPORATE"
    auth_required = true
    idle_time_in_minutes = 720
    display_time_unit = "HOUR"
    surrogate_ip = true
    xff_forward_enabled = true
    ofw_enabled = true
    ips_control = true
    ip_addresses = [ zia_traffic_forwarding_static_ip.this.ip_address ]
    depends_on = [ zia_traffic_forwarding_static_ip.this, zia_traffic_forwarding_gre_tunnel.this]
}
}
```
Notice the depends_on meta-argument used within the resources to inform Terraform of the order of operations.
This has also been documented in the provider documentation in the Terraform Registry [Here](https://registry.terraform.io/providers/zscaler/zia/latest/docs/resources/zia_traffic_forwarding_gre_tunnel)

**Comment by alasta** [comment]
In my code, this option this true or false same problem ....
The first deployment is OK but not the nexts.
I try to debug.

**Comment by alasta** [comment]
The original issue is solved.
