### ISSUE TITLE
Error with overlapping sublocation names

### ISSUE THREAD

**Issue by jxg81** [zscaler/terraform-provider-zia#223]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform 1.4.2

### Affected Resource(s)

ZIA Location Management Data Source

### Terraform Configuration Files

data “zia_location_management” “location” {
  name     = “test”

### Debug Output

{"@level":"error","@message":"Error: json: cannot unmarshal array into Go struct field Locations.ports of type string","@module":"terraform.ui","@timestamp":"2023-04-14T04:10:21.609067Z","diagnostic":{"severity":"error","summary":"json: cannot unmarshal array into Go struct field Locations.ports of type string","detail":"","address":"module.application[\"app_web\"].data.zia_location_management.location[\"test\"]","range":{"filename":"modules/apps/main.tf","start":{"line":15,"column":43,"byte":260},"end":{"line":15,"column":44,"byte":261}},"snippet":{"context":"data \"zia_location_management\" \"location\"","code":"data \"zia_location_management\" \"location\" {","start_line":15,"highlight_start_offset":42,"highlight_end_offset":43,"values":[]}},"type":"diagnostic"}

### Expected Behavior

Ability to select sublocations based on parent-location/sub-location pair

### Actual Behavior

Error with overlapping sublocation names

### Steps to Reproduce

Create two locations with overlapping sublocaiton names

See attached screenshot for zia config
![image_720](https://user-images.githubusercontent.com/48175613/231942863-f8509328-61fd-418c-8d12-4ca5b9121f37.png)

**Comment by willguibr** [comment]
Hi @jxg81 
This issue has been addressed as part the PR #227 and a new minor release will be published in the next couple of days.
Thank you.
