### ISSUE TITLE
Error when hitting API rate limit.

### ISSUE THREAD

**Issue by dli-spoton** [zscaler/terraform-provider-zia#232]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.4.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/zscaler/zia v2.5.2
```

### Affected Resource(s)

- data.zia_group_management (Might be a general issue with all data sources)

### Terraform Configuration Files

Will throw an error generally:
```hcl
locals {
  groups = toset([
    "Group1", "Group2", "Group3"
  ])
}

data "zia_group_management" "each" {
  for_each = local.groups
  name     = each.value
}

output "out" {
  value = data.zia_group_management.each
}

```
Will work:
```hcl

data "zia_group_management" "one" {
  name = "Group1"
}
resource "time_sleep" "one" {
  depends_on      = [data.zia_group_management.one]
  create_duration = "1s"
}
data "zia_group_management" "two" {
  name = "Group2"
  depends_on = [
    time_sleep.one
  ]
}
resource "time_sleep" "two" {
  depends_on      = [data.zia_group_management.two]
  create_duration = "1s"
}
data "zia_group_management" "three" {
  name = "Group3"
  depends_on = [
    time_sleep.two
  ]
}
resource "time_sleep" "three" {
  depends_on      = [data.zia_group_management.three]
  create_duration = "1s"
}
output "out" {
  value = {
    one   = data.zia_group_management.one
    two   = data.zia_group_management.two
    three = data.zia_group_management.three
  }
}
```

### Expected Behavior

Return group data.

### Actual Behavior

```
Error: json: cannot unmarshal object into Go value of type []usermanagement.Groups
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I'm guessing the data source isn't handling the rate limits on the API endpoints correctly.
Works if you set `-parallelism=1`, but seems like a poor work around.

### References

[ZIA - About Rate Limiting](https://help.zscaler.com/zia/about-rate-limiting)
[ZIA - API Rate Limit Summary](https://help.zscaler.com/zia/api-rate-limit-summary)

**Comment by willguibr** [comment]
Hi @dli-spoton 
I am unable to reproduce the error you're indicating. Using the snippet configuration your provided above, the search is working as expected. Also, it is not clear why rate limits is being raised as an issue along with a panic message as both seem unrelated.
``Error: json: cannot unmarshal object into Go value of type []usermanagement.Groups``

Please provide debug logs via secure method by setting the following environment variables:

export ZSCALER_SDK_LOG=true
export ZSCALER_SDK_VERBOSE=true
export TF_LOG="DEBUG"
export TF_LOG_PATH="terraform.log"

You can send the logs to: wguilherme@you_know_the_rest.com ;)
