### ISSUE TITLE
Get stuck importing zia_url_category from zscalerbeta

### ISSUE THREAD

**Issue by shmoeshmeps** [zscaler/terraform-provider-zia#247]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v1.4.6
on linux_amd64
+ provider registry.terraform.io/zscaler/zia v2.5.5
```

### Affected Resource(s)

- zia_url_category

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    zia = {
      source = "zscaler/zia"
      version = "2.5.5"
    }
  }
}

provider "zia" {
  # Configuration options
 zia_cloud = "zscalerbeta"
}
```

### Debug Output
https://gist.github.com/shmoeshmeps/b2d33479099991158b33113373beb991

### Expected Behavior
I was expecting it to fetch the resource and import it - this is what happens when I try on out zscalerthree account
OR if an error show the issue
OR timeout after some point
OR accept keypresses to terminate the process

### Actual Behavior
If no TF_LOG set, just sits on `zia_url_categories.OTHER_ADULT_MATERIAL: Importing from ID `
If TF_LOG=TRACE you can see the flapping between the  "is waiting for" messages
Ignores all Ctrl-C attempts (although notices them in the trace logs)

### Steps to Reproduce
- Have a clean install with no state
- Use the above config
- Put creds into env vars
- create skeleton resource in .tf like:
```
resource "zia_url_categories" "OTHER_ADULT_MATERIAL" {
  # (resource arguments)
}
```
- run command `terraform import zia_url_categories.OTHER_ADULT_MATERIAL OTHER_ADULT_MATERIAL`

### Important Factoids

- Creds and API key work from same source using postman to zscalerbeta
- identical setup works fine with zscalerthree
- issue occurs with any url category I import

**Comment by willguibr** [comment]
@shmoeshmeps 
Terraform import won't import built-in (predefined) categories. However, there's an issue where Terraform currently only imports based on ID; however, URL Category IDs are equivalent to the category name according to the API.
The Import is successful when using the [Zscaler Terraformer Tool](https://github.com/zscaler/zscaler-terraformer), which is the recommended approach.

Install the tool as per the README instructions, and then execute the following command after setting up your credentials

``zscaler-terraformer import --resources="zia_url_categories"``

William

**Comment by shmoeshmeps** [comment]
Hi William,

Thanks - but unfortunately I can't use the above tool in our environment due to [this issue](https://github.com/zscaler/zscaler-terraformer/issues/102).

However, after sniffing some packets I could see the attempts to make a connection to zscalerbeta.net being reset by a firewall policy. It seems there's no mechanism in this instance which signals back to TF or the provider to abort, it just keeps retrying.

Once I sorted the firewall policy out, my initial attempt at importing worked fine so I'll close this issue. Thanks for the attention.
