### ISSUE TITLE
Error to deploy GRE tunnel

### ISSUE THREAD

**Issue by alasta** [zscaler/terraform-provider-zia#249]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.2.2
Zia provider 2.5.5
### Affected Resource(s)

- zia_traffic_forwarding_gre_tunnel

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
data "zia_traffic_forwarding_gre_vip_recommended_list" "this"{
    source_ip = zia_traffic_forwarding_static_ip.this.ip_address
    required_count = 2
}

data "zia_gre_internal_ip_range_list" "this"{
    required_count = 10
}

resource "zia_traffic_forwarding_static_ip" "this"{
    ip_address =  "My_IP"
    routable_ip = true
    comment = "Created with Terraform"
    geo_override = true
    latitude = 49.0526
    longitude = -122.8291
}

resource "zia_traffic_forwarding_gre_tunnel" "this" {
  source_ip      = zia_traffic_forwarding_static_ip.this.ip_address
  comment        = "GRE Tunnel Created with Terraform"
  within_country = false
  country_code   = "CA"
  ip_unnumbered  = false
  primary_dest_vip {
    datacenter = data.zia_traffic_forwarding_gre_vip_recommended_list.this.list[0].datacenter
    virtual_ip = data.zia_traffic_forwarding_gre_vip_recommended_list.this.list[0].virtual_ip
  }
  secondary_dest_vip {
    datacenter = data.zia_traffic_forwarding_gre_vip_recommended_list.this.list[1].datacenter
    virtual_ip = data.zia_traffic_forwarding_gre_vip_recommended_list.this.list[1].virtual_ip
  }
  depends_on     = [zia_traffic_forwarding_static_ip.this]
}
```

### Debug Output

```
│ Error: FAILED: POST, https://zsapi.[masked].net/api/v1/greTunnels, 400, 400 , {"code":"INVALID_INPUT_ARGUMENT","message":"Invalid primary data center VIP."}, api responded with code: 400
│ 
│   with zia_traffic_forwarding_gre_tunnel.this,
│   on main-tunnels.tf line 59, in resource "zia_traffic_forwarding_gre_tunnel" "this":
│   59: resource "zia_traffic_forwarding_gre_tunnel" "this" {
│
```
### Expected Behavior

I have a basic configuration, but by default, the primary and secondary datacenter are the same, the best practice is 2 differents datacenter.
Then I add the "primary_dest_vip" and "secondary_dest_vip" with the configuration in official documentation, but not working.

### Steps to Reproduce

Use the official documentation config (or see the " Terraform Configuration Files").
1. `terraform apply`

**Comment by willguibr** [comment]
Hi @alasta 
The documentation needs updating.
In the previous versions we have implemented the ability to create GRE tunnels without the need to specify the primary_dest_vip and secondary_dest_vip, so that the upstream API automatically defines the proper VIPs for you. 

You can create a GRE tunnel with the following configuration snippet below

```hcl
resource "zia_traffic_forwarding_gre_tunnel" "this" {
  source_ip      = zia_traffic_forwarding_static_ip.this.ip_address
  comment        = "GRE Tunnel Created with Terraform"
  within_country = true
  country_code   = "CA"
  ip_unnumbered  = false
  depends_on     = [zia_traffic_forwarding_static_ip.this]
}
```
We'll investigate options to allow for custom definitions of primary and secondary VIPs in future versions.

Regards,

William

**Comment by alasta** [comment]
Hi,
it work if I not specify the Data center, but by default the API set the same Datacenter, the best practice is 2 differents datacenter to GRE.
Have you got a date to this option ?
best regards

**Comment by willguibr** [comment]
The API will automatically set 2 different datacenter VIPs for you, but due to some apparent API limitations it won't let you select different DC Country VIPs. i.e SYD3 and SIN4.
We don't currently have an exact date at the moment as it may require API adjustments, but I am expecting in the next 2 months or so.
Regards
