### ISSUE TITLE
Data source  zia_user_management fails on converting user data

### ISSUE THREAD

**Issue by piotrszlenk** [zscaler/terraform-provider-zia#261]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform version 1.4.4

```
terraform -v
Terraform v1.4.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.56.0
+ provider registry.terraform.io/hashicorp/vault v3.19.0
+ provider registry.terraform.io/zscaler/zia v2.4.6

Your version of Terraform is out of date! The latest version
is 1.5.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

Data Source: zia_user_management

### Terraform Configuration Files

```hcl
data "zia_user_management" "does_not_exists" {
  name = "Adam Ashcroft"
}

data "zia_user_management" "exists" {
  name = "piotr.szlenk"
}
```

### Debug Output

https://gist.github.com/piotrszlenk/b91edce91010c1f17f7f6c42d322f5e0

### Expected Behavior

Data source should return details of a particular user. Data source fails as expected when user does not exist but also fails when user exists.

### Actual Behavior

```
│ Error: no user found with name: Adam Ashcroft
│ 
│   with data.zia_user_management.does_not_exists,
│   on data.tf line 4, in data "zia_user_management" "does_not_exists":
│    4: data "zia_user_management" "does_not_exists" {
│ 


│ Error: Invalid address to set: []string{"groups", "0", "extensions"}
│ 
│   with data.zia_user_management.exists,
│   on data.tf line 8, in data "zia_user_management" "exists":
│    8: data "zia_user_management" "exists" {
│ 
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I am experimenting with zscalerbeta.net. I can't tell if this works on regular tenants as I have no access to them.

**Comment by willguibr** [comment]
This issue has been addressed in previous versions. Please update your configuration to the latest version v2.6.1 and test again to ensure it's working as expected.
Thanks
