### ISSUE TITLE
Predefined DLP Dictionary with Space in Engine  

### ISSUE THREAD

**Issue by tiwari3010** [zscaler/terraform-provider-zia#274]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```ruby
sh-3.2$ terraform -v
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/zscaler/zia v2.6.1
```

### Affected Resource(s)

- zia_dlp_engines

### Terraform Configuration Files

```hcl
locals {
  engine_expression = join(
    " ${var.condition} ",
    [for idx, dict_name in var.zia_dlp_dictionaries : "(D${element(data.zia_dlp_dictionaries.zia_dlp_dictionaries_name, idx).id}.S > ${var.dictionary_threshold[idx]})"]
  )
}

resource "zia_dlp_engines" "dlp_engine" {
  name        = "${var.dlp_engine_name}_tf"
  description = "Terraform ${var.dlp_engine_description}"
  engine_expression = "(${local.engine_expression})"
  custom_dlp_engine = true
}

dlp_engine_name        = "us_cai_dlp_engine"
dlp_engine_description = "us_cai_dlp_engine"
zia_dlp_dictionaries   = ["Weapons", "Gambling",  "Social Security Numbers (US)"]
dictionary_threshold   = ["100", "5", "50"]
condition              = "OR"

data "zia_dlp_dictionaries" "zia_dlp_dictionaries_name" {
  count = length(var.zia_dlp_dictionaries)
  name  = var.zia_dlp_dictionaries[count.index]
}
```

### Panic Output

When using predefined directories with SPACES in them, its getting below error
```hcl
╷
│ Error: no dictionary found with name: Social Security Numbers (US)
│ 
│   with data.zia_dlp_dictionaries.zia_dlp_dictionaries_name[2],
│   on data.tf line 1, in data "zia_dlp_dictionaries" "zia_dlp_dictionaries_name":
│    1: data "zia_dlp_dictionaries" "zia_dlp_dictionaries_name" {
│ 
╵
```

### Expected Behavior

This should generate engine_expression = "((D45.S > 0) OR (D46.S > 0) OR (D62.S > 50))"

### Actual Behavior

Getting `│ Error: no dictionary found with name: Social Security Numbers (US)`

### Steps to Reproduce

1. `terraform apply`

Any Prefinded Dictionary with SPACE is not generating the associated ID and use it when creating the engine.

**Comment by willguibr** [comment]
@tiwari3010 There are some API limitations regarding search containing spaces that need to be investigated. In the meantime, we recommend to clone the built-in dictionary i.e Social Security Numbers (US) and set the name with underscores or dashes as Social_Security_Numbers_US.
Regards

**Comment by tiwari3010** [comment]
Thank you William, I thought of doing that exactly.

**Comment by atul1140** [comment]
╷
**│ Error: time stamp or api key doesn't have required sizes**
│
│   with module.DLPs.data.zia_dlp_dictionaries.example1,
│   on ..\modules\vinci_dlp_dictionary\datasource.tf line 1, in data "zia_dlp_dictionaries" "example1":
│    1: data "zia_dlp_dictionaries" "example1"{


why this error occurs?

**Comment by atulevertz** [comment]
Error: time stamp or api key doesn't have required sizes
│
│   with module.DLPs.data.zia_dlp_dictionaries.example1,
│   on ..\modules\vinci_dlp_dictionary\datasource.tf line 1, in data "zia_dlp_dictionaries" "example1":
│    1: data "zia_dlp_dictionaries" "example1"{

Why is this error coming ?
