### ISSUE TITLE
Zia module not working 

### ISSUE THREAD

**Issue by atulevertz** [zscaler/terraform-provider-zia#292]
Hi ! I am writing terraform code for zia using module but when i am calling the resources using module as i used to do with AWS.   I get errors 
Un-successful request with status code : 400

Can anyone please help me sharing code where you have called module. I can refer that and proceed towards success

**Comment by willguibr** [comment]
@atulevertz 
Please provide exact error message along with debug logs, resource name you're trying to provision etc.
Set the following environment variables prior to executing Terraform again, and then provide the log output for analysis.
export ZSCALER_SDK_LOG=true
export ZSCALER_SDK_VERBOSE=true
export TF_LOG="TRACE"
export TF_LOG_PATH="terraform.log"

**Comment by atulevertz** [comment]
hi @willguibr 
 i need your urgent help. please provide me sample ZIA-terraform module which can help me refer to write for my environment. 
I can see the modules available but how to call those modules are not available at all.
I have worked on AWS terraform and the module i a following with ZIA-TF in AWS-TF , it works in AWS-TF ...



I am calling the module like below:

module "dlps" {
    source = "../modules/dlp_dictionary"
    api_key  = var.api_key
  
}



module "dlp_engine_policy" {
    source = "../modules/vinci_dlp_engine"
    api_key = var.api_key
  
}

**Comment by willguibr** [comment]
Please contact me via email so we can set up some time to discuss. The question/problem you're stating is unclear and cannot be answered via this issue. Please email at wguilherme@zscaler.com
Second I am on PST timezone.
William
