### ISSUE TITLE
vpn_credental_id is not exportable from zia_traffic_forwarding_vpn_credentials

### ISSUE THREAD

**Issue by panepintog** [zscaler/terraform-provider-zia#326]
### Terraform Version

Terraform v1.7.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.47.0
+ provider registry.terraform.io/hashicorp/azurerm v3.95.0
+ provider registry.terraform.io/zscaler/zia v2.7.33

### Affected Resource(s)

- zia_traffic_forwarding_vpn_credentials
- zia_location_management

### Terraform Configuration Files

```hcl
resource "zia_traffic_forwarding_vpn_credentials" "location_1_psk" {
    type            = "UFQDN"
    fqdn            = "email@example.com"
    comments        = "Terraform managed"
    pre_shared_key  = var.zia_psk
}
```

```hcl

resource "zia_location_management" "location_1" {
    name                        = "location_1"
    description                 = "Managed by Terraform"
    country                     = "AUSTRALIA"
    tz                          = "AUSTRALIA_MELBOURNE"
    auth_required               = false # Not required for server type locations
    profile                     = "SERVER" # Must be uppercase
    idle_time_in_minutes        = 720
    display_time_unit           = "HOUR"
    surrogate_ip                = false
    xff_forward_enabled         = false
    ofw_enabled                 = true
    ips_control                 = true
    vpn_credentials {
       id = zia_traffic_forwarding_vpn_credentials.location_1_psk.vpn_credental_id
       type = zia_traffic_forwarding_vpn_credentials.location_1_psk.type
    }
    depends_on = [ zia_traffic_forwarding_vpn_credentials.location_1_psk ]
```

### Error Output
```
│ Error: Unsupported attribute
│ 
│   on locations.tf line 15, in resource "zia_location_management" "location_1":
│   15:        id = zia_traffic_forwarding_vpn_credentials.location_1_psk.vpn_credental_id
│ 
│ This object has no argument, nested block, or exported attribute named
│ "vpn_credental_id".
╵
```
### Expected Behavior

It should have created the location as per docs.

### Actual Behavior

Unrecoverable error

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### Important Factoids

This works on the previous release, hardcoding `provider registry.terraform.io/zscaler/zia 2.7.32` resolves the issue.

Additionally, `vpn_credental_id` is misspelled, it should be `vpn_credential_id`
I suggest to add `vpn_credential_id` as well in the next release to avoid confusion amongst users when debugging

### References
https://registry.terraform.io/providers/zscaler/zia/latest/docs/resources/zia_location_management

**Comment by willguibr** [comment]
Hi @panepintog vpn_credential_id is a computed attribute and should not used within the configuration scope.
In addition if the purpose is to import existing ZIA configuration we recommend using our dedicated importing tool Zscaler Terraform found here: https://github.com/zscaler/zscaler-terraformer
Regards

**Comment by panepintog** [comment]
Hi @willguibr ,

Thank you for your reply.

When you say "should not be used within the configuration scope" what do you mean? What should be used as `id` in the `vpn_credentials` stanza of the `zia_location_management` resource ?

[As per documentation](https://registry.terraform.io/providers/zscaler/zia/latest/docs/resources/zia_location_management)  a VPN credential ID (which is a computed resource) is required when IPs are not defined. In the same documentation, the example illustrates the use of `vpn_credential_id` as value of `id` under `vpn_credentials`; see:
```
    vpn_credentials {
       id = zia_traffic_forwarding_vpn_credentials.usa_sjc37.vpn_credental_id
       type = zia_traffic_forwarding_vpn_credentials.usa_sjc37.type
    }
```
----
Quote from your documentation:
[vpn_credentials](https://registry.terraform.io/providers/zscaler/zia/latest/docs/resources/zia_location_management#vpn_credentials)

    id - (Optional) VPN credential resource id. The value is required if ip_addresses are not defined.

any clarification is appreciated

**Comment by willguibr** [comment]
@panepintog  You can use either `id` or `vpn_id` as the exportable id information within the vpn_credentials block. Both will work.
We have updated the documentation as of today during the release of v2.8.0.
```hcl
resource "zia_location_management" "usa_sjc37"{
    name = "USA_SJC_37"
    description = "Created with Terraform"
    country = "UNITED_STATES"
    tz = "UNITED_STATES_AMERICA_LOS_ANGELES"
    xff_forward_enabled = true
    ofw_enabled = true
    ips_control = true
    ip_addresses = [ zia_traffic_forwarding_static_ip.usa_sjc37.ip_address ]
    depends_on = [ zia_traffic_forwarding_static_ip.usa_sjc37, zia_traffic_forwarding_vpn_credentials.usa_sjc37 ]
    vpn_credentials {
       id = zia_traffic_forwarding_vpn_credentials.usa_sjc37.id
       type = zia_traffic_forwarding_vpn_credentials.usa_sjc37.type
       ip_address = zia_traffic_forwarding_static_ip.usa_sjc37.ip_address
    }
}

resource "zia_traffic_forwarding_vpn_credentials" "usa_sjc37"{
    type        = "IP"
    ip_address  =  zia_traffic_forwarding_static_ip.usa_sjc37.ip_address
    depends_on = [ zia_traffic_forwarding_static_ip.usa_sjc37 ]
    comments    = "Created via Terraform"
    pre_shared_key = "*************"
}

resource "zia_traffic_forwarding_static_ip" "usa_sjc37"{
    ip_address =  "1.1.1.1"
    routable_ip = true
    comment = "SJC37 - Static IP"
    geo_override = false
}
```

**Comment by panepintog** [comment]
That works, thank you.
It would be good to keep the docs updated to avoid these situations.
