### ISSUE TITLE
zia resource for Local group missing unable to bind sublocations to static / dynamic groups

### ISSUE THREAD

**Issue by vitalemazo** [zscaler/terraform-provider-zia#355]
Hello Zia Team,

I have found zia resource to create location group is missing in terraform registry & Zia Github page. I see there data block but not a resource.

Is  it possible to add this resource? or at least create a workaround to add groups to sublocations via terraform

 "Was there an Update to this I have 20 parent locations and 100's of sublocations the sublocations require the reference to the static or dynamic groups how can this be done if there is no argument in location management resource for the data

https://help.zscaler.com/zia/location-management#/locations/groups-get

![173128539-f98cb417-1db3-4dbd-a252-e3d79fe26194](https://github.com/zscaler/terraform-provider-zia/assets/22359630/f21110c4-e583-4ae3-a7bb-8fa8db9953cd)

Current code example 

```
resource "zia_location_management" "sublocation1" {
  name                 = "Test Sub-location 1"
  description          = "Created with Terraform"
  country              = "UNITED_STATES"
  tz                   = "UNITED_STATES_AMERICA_LOS_ANGELES"
  auth_required        = true
  idle_time_in_minutes = 720
  display_time_unit    = "HOUR"
  surrogate_ip         = true
  xff_forward_enabled  = true
  ofw_enabled          = true
  ips_control          = true
  ip_addresses         = ["192.168.4.2"]
  parent_id            = zia_location_management.usa_sjc37.id
  What can I use = to tell the sublocation it is part of a static / dynamic group ???? <---------
  
}
```

It seems the API has the response needed see below how can this be referenced in terraform 
![api](https://github.com/zscaler/terraform-provider-zia/assets/22359630/fb460cc7-fb41-4716-a864-eabb1abe69ea)

**Comment by willguibr** [comment]
@vitalemazo 
The API methods for POST/PUT/DELETE for location groups is not publicly available, hence it's not covered under the terraform provider.
Until the APIs are public (For any resources) we have no plans to include in the provide or GO SDK. If this is a priority please contact your account team and raise an enhancement request with the appropriate teams for consideration.
Zscaler DevRel.

**Comment by vitalemazo** [comment]
![api workaround](https://github.com/zscaler/terraform-provider-zia/assets/22359630/26d7fffe-a280-4073-b143-bb04c34bdd16)
Will Thanks can you give a work aroun so that my terraform executions of sublocations don't keep overwriting the " location groups " , am I supposed to ignore resource block changes then ? what is the. work around ?

**Comment by willguibr** [comment]
Please raise a support ticket via the formal process described in the following page: https://github.com/zscaler/terraform-provider-zia/blob/master/docs/guides/support.md

**Comment by vitalemazo** [comment]
Case Number: 04991787 - Issue with Sublocation "Static Group" Binding


Will, regarding Case Number: 04991787, which I thought had reached your team. My overarching question is how we should handle gaps like this when we encounter them. 

In my current situation, I have many sublocations that require "static group" binding. This becomes a significant issue with multiple 70 -1000 sublocations. If it were just one sublocation, it might not be as problematic. However, since the zscaler zia provider is advertised as being capable of using location management groups, I would expect that all arguments are available to fully manage the specific resource, in this case, the location management resource and the sublocation attributes.

This is just one instance, but I assume there could be hundreds of similar examples. Is the ZIA Terraform provider and API not being developed at the same cadence as the UI development?

I look forward to your guidance on how to address this issue and insight into how organizations that plan to use mass resources management with code can use a provider like this when there are gaps , at the minimum I need to be able to lifecycle ignore this "group location " during TF deployments so I don't overwrite UI group location changes for sublocations.

Thanks for any assistance.

**Comment by willguibr** [comment]
Please upgrade your provider configuration to v2.91.2.
The new version includes the options for Manual and Dynamic location groups.
See official provider [documentation](https://registry.terraform.io/providers/zscaler/zia/latest/docs/resources/zia_location_management) for usage examples

**Comment by vitalemazo** [comment]
Thank you was this a one of midnight fix appreciate  it , but the question remains on the api cadence compared to the ui/ product development . Thank you again

**Comment by vitalemazo** [comment]
Doing some debugging and while I can see terraform picking up the static group and its ID its not making its way to the zscaler UI ??

`~/untitled folder/enviornments/dev ❯ terraform apply -auto-approve                                                                           ☁ COUNTRY Financial Sandbox at 07:20:34 PM

data.zia_location_groups.this: Reading...
data.zia_location_groups.static_location_groups["SDWAN_test"]: Reading...
module.static_ips["Aurora Non-Productiontest"].zia_traffic_forwarding_static_ip.static_ip["208.74.230.9"]: Refreshing state... [id=3670210]
data.zia_location_groups.this: Read complete after 1s [name=SDWAN_test]
module.parent_locations["Aurora Non-Productiontest"].zia_location_management.parent_locations: Refreshing state... [id=107565388]
data.zia_location_groups.static_location_groups["SDWAN_test"]: Read complete after 1s [name=SDWAN_test]
module.sublocations["Aurora Non-Productiontest"].data.zia_location_groups.static_location_groups["ADFStest - Active Directory Federation Services"]: Reading...
module.sublocations["Aurora Non-Productiontest"].data.zia_location_groups.static_location_groups["ADFStest - Active Directory Federation Services"]: Read complete after 0s [name=SDWAN_test]
module.sublocations["Aurora Non-Productiontest"].zia_location_management.sublocations["ADFStest - Active Directory Federation Services"]: Refreshing state... [id=107565391]

Changes to Outputs:
  ~ debug_sublocations = {
      ~ "Aurora Non-Productiontest" = {
          + static_location_groups = [
              + {
                  + group_ids = [
                      + 107556531,
                    ]
                  + groups    = [
                      + "SDWAN_test",
                    ]
                  + name      = "ADFStest - Active Directory Federation Services"
                },
            ]
            # (1 unchanged attribute hidden)
        }
    }

You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

debug_sublocations = {
  "Aurora Non-Productiontest" = {
    "static_location_groups" = [
      {
        "group_ids" = [
          107556531,
        ]
        "groups" = tolist([
          "SDWAN_test",
        ])
        "name" = "ADFStest - Active Directory Federation Services"
      },
    ]
    "sublocations" = tolist([
      {
        "description" = "Sublocation for ADFS_Active_Directory_Federation_Services"
        "ip_addresses" = tolist([
          "10.111.111.11",
        ])
        "name" = "ADFStest - Active Directory Federation Services"
        "profile" = "SERVER"
        "static_location_groups" = tolist([
          "SDWAN_test",
        ])
      },
    ])
  }
}
~/untitled folder/enviornments/dev ❯ terraform output debug_sublocations                                                                     ☁ COUNTRY Financial Sandbox at 07:20:38 PM

{
  "Aurora Non-Productiontest" = {
    "static_location_groups" = [
      {
        "group_ids" = [
          107556531,
        ]
        "groups" = tolist([
          "SDWAN_test",
        ])
        "name" = "ADFStest - Active Directory Federation Services"
      },
    ]
    "sublocations" = tolist([
      {
        "description" = "Sublocation for ADFS_Active_Directory_Federation_Services"
        "ip_addresses" = tolist([
          "10.111.111.11",
        ])
        "name" = "ADFStest - Active Directory Federation Services"
        "profile" = "SERVER"
        "static_location_groups" = tolist([
          "SDWAN_test",
        ])
      },
    ])
  }
}
~/untitled folder/enviornments/dev ❯`

**Comment by vitalemazo** [comment]
Basically the changes are not happening although the configuration works .
[Uploading terraform-debug.log…]()
