### ISSUE TITLE
DLP Dictionary Clone error for Driver's License

### ISSUE THREAD

**Issue by tiwari3010** [zscaler/terraform-provider-zia#360]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

- ZIA v2.91.4
- Terraform v1.5.7 

### Terraform Configuration Files

Trying to clone Driver’s License (United States) dictionary using terraform.

```hcl
resource "zia_dlp_dictionaries" "dlp_dictionaries" {
  name        = "${var.dlp_dictionaries_name}_predefined_dic_tf"
  description = "Terraform ${var.dlp_dictionaries_description}_predefined_prod_dic"
  dynamic "phrases" {
    for_each = var.dlp_phrases
    content {
      action = "PHRASE_COUNT_TYPE_ALL"
      phrase = phrases.value
    }
  }
  custom_phrase_match_type = "MATCH_ALL_CUSTOM_PHRASE_PATTERN_DICTIONARY"
  dictionary_type          = "PATTERNS_AND_PHRASES"
  dict_template_id         = var.dict_template_id
  confidence_threshold     = var.confidence_threshold
}
```

```ruby
dlp_dictionaries_name        = "driver_license_us_high"
dlp_dictionaries_description = "Driver license Numbers for US Where Confidence Level is High"
dlp_phrases                  = []
dict_template_id             = "170"
confidence_threshold         = "CONFIDENCE_LEVEL_HIGH" # "CONFIDENCE_LEVEL_LOW", "CONFIDENCE_LEVEL_MEDIUM", "CONFIDENCE_LEVEL_HIGH"
````
### Panic Output

zia_dlp_dictionaries.dlp_dictionaries: Creating...
╷
│ Error: FAILED: POST, https://zsapi.zscalertwo.net/api/v1/dlpDictionaries, 400, 400 , {"message":"Atleast 1 hierarchical identifier should be selected for hierarchical dictionaries"}, api responded with code: 400
│ 
│   with zia_dlp_dictionaries.dlp_dictionaries,
│   on main.tf line 1, in resource "zia_dlp_dictionaries" "dlp_dictionaries":
│    1: resource "zia_dlp_dictionaries" "dlp_dictionaries" {

### Expected Behavior

The dictionary should be created as a clone for Driver's License. 

### Steps to Reproduce

1. `terraform apply`

gives below error
```ruby
│ Error: FAILED: POST, https://zsapi.zscalertwo.net/api/v1/dlpDictionaries, 400, 400 , {"message":"Atleast 1 hierarchical identifier should be selected for hierarchical dictionaries"}, api responded with code: 400
```
### References
```ruby
as per the documentation hierarchical identifiers needs to be passed


hierarchicalIdentifiers
array[string]
The list of identifiers selected within a DLP dictionary of hierarchical type. Each identifier represents a sub-dictionary that consists of specific patterns. To retrieve the list of identifiers that are available for selection within a specific hierarchical dictionary, send a GET request to /dlpDictionaries/{dictId}/predefinedIdentifiers.

To learn about hierarchical dictionaries, see [Configuring the URL Filtering Policy](https://help.zscaler.com/zia/understanding-predefined-dlp-dictionaries).

Note: This field is applicable to predefined hierarchical dictionaries, such as the Driver’s License (United States), Passport Number (European Union), and Credentials and Secrets dictionaries or their clones.
```

**Comment by willguibr** [comment]
@tiwari3010 `hierarchical_identifiers` is a new attribute, and not yet supported in the provider. It will be included in the next release.
Thank you
