### ISSUE TITLE
Issue with Location Management Resource

### ISSUE THREAD

**Issue by edukinara** [zscaler/terraform-provider-zia#363]
The Ports field of the zia_location_management datasource appears to have the wrong type. Based on API response, should an array of integers.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.9.4

### Affected Resource(s)

- zia_location_management

### Debug Output

```
│ Error: json: cannot unmarshal array into Go struct field Locations.ports of type string
│
│   with data.zia_location_management.gbbedalea2jnzzz,
│   on data_zia_location_management.tf line 1, in data "zia_location_management" "gbbedalea2jnzzz":
│    1: data "zia_location_management" "gbbedalea2jnzzz" {
```

**Comment by edukinara** [comment]
@willguibr this is still an issue. I believe the type should be a list of integers, not list of strings.

**Comment by willguibr** [comment]
@edukinara 
please give it another try now with the v3.0.1. Apologies for the inconvenience.
Zscaler DevRel
