### ISSUE TITLE
Plugin keeps crashing

### ISSUE THREAD

**Issue by justinjocewicz** [zscaler/terraform-provider-zia#376]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

**Terraform v1.9.8
on windows_386
+ provider registry.terraform.io/zscaler/zia v3.0.6**

### Affected Resource(s)

- zia_xxx

Happens with data calls or anything

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

**main.tf**
# IP Destination Group of Type DSTN_FQDN
resource "zia_firewall_filtering_destination_groups" "dstn_fqdn" {
  name        = "Example Destination FQDN"
  description = "Example Destination FQDN"
  type        = "DSTN_FQDN"
  addresses = [ "test1.acme.com", "test2.acme.com", "test3.acme.com" ]
}

**provider.tf**
terraform {
  required_providers {
    zia = {
      source = "zscaler/zia"
      version = "3.0.6"
    }
  }
}

provider "zia" {
 username      = **removed**
 password      = **removed**
  api_key       = "**removed**
  zia_cloud     = "zscalertwo"
}

### Debug Output

https://gist.github.com/justinjocewicz/2c48d255e14db5d137258f30f1620b4d

### Expected Behavior

To apply the resources

### Actual Behavior

plugin crash

### Steps to Reproduce

1. create any basic code
2.  `terraform plan
3.  terraform apply

plugin will die.  Tried all provider versions from 3.0.0 to 3.0.6

**Comment by willguibr** [comment]
@justinjocewicz 
please ensure that you have the correct version of the Terraform software installed on your Windows machine.
If your Windows is 64bit make sure you're installing the Terraform AMD64 binary before executing our provider. 
The panic indicates that there is a misalignment between your OS architecture and the Terraform software installed. Most likely you are running Terraform 32Bit. You can easily check that by executing `terraform version`
https://developer.hashicorp.com/terraform/install?product_intent=terraform#windows

If the problem persists please raise a ticket with our global support team and we will investigate further.

Zscaler DevRel

**Comment by justinjocewicz** [comment]
wow..I am slow @willguibr ...thank you.  Wow..lol
