### ISSUE TITLE
ZIA activation - depends on other ressources

### ISSUE THREAD

**Issue by romaric1** [zscaler/terraform-provider-zia#95]
Hello , Thanks you for the terraform provider it's really helpful.
I found yesterday this ressources https://github.com/zscaler/terraform-provider-zia/blob/master/examples/zia_activation/main.tf .
Can we apply "a new" **the zia activation ressource** when we want to update a url category ressources to add new url 

resource "zia_url_categories" "default" {
  super_category  = var.super_category
  configured_name = var.configured_name
  description     = var.description
  keywords        = var.keywords
  custom_category = true
  type            = "URL_CATEGORY"
  urls            = ["www.google.com","www.zscaler.com","docs.paloaltonetworks.com"]
}

I want to use **zia activate ressource** when i update urls here , it's something possible or not ?

Thanks you in advance

**Comment by willguibr** [comment]
Hi @romaric1 If I understand your question correctly, you want to add new URLs to the same url category rule, and then run the activate again so it an take effect. The resource example you are referring to, is possible; however, the recommended way is by following what is described in the guide here: https://registry.terraform.io/providers/zscaler/zia/latest/docs/guides/zia-activator-overview 
As of right now, Terraform does not perform post activation after apply; hence, it needs to be handled out-of-band, by compiling the ziaActivator utility placing that in the executable PATH of your machine.

Finally, you can then run the ziaActivator utility as part of your terraform apply like that: `terraform init && terraform apply --auto-approve && ziaActivator`

Let me know if this works for you.
