### ISSUE TITLE
Can't Import Provider, Gives error  Error while installing zscaler/zia v2.0.2: checksum list has unexpected SHA-256 hash

### ISSUE THREAD

**Issue by maajin** [zscaler/terraform-provider-zia#96]
Getting Below error why trying to import the provider.

╷
│ Error: Failed to install provider
│
│ Error while installing zscaler/zia v2.0.2: checksum list has unexpected SHA-256 hash
│ 7904c44c1cef561270a3859ea3d8d43b33ea322d220dee49eb6790d0186356df (expected
│ 57e0e3bd2a2c1d246d49140c56afe8d64594bc23a95f1969bb2c9a9ec5d34133)

**Comment by willguibr** [comment]
Hi @maajin Please use the latest version v2.0.3. I am working with Hashicorp to resolve this issue.
Thank you
